### ISSUE TITLE
Blurry GUI Scaling

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#111]
**Describe the bug**
UI doesnt keep clarity when scaling with surface. 

Discussed with with pygame gui dev [here](https://github.com/MyreMylar/pygame_gui/issues/158#issuecomment-701966091).

**Platform:**
 - OS: Windows 10
 - Engine Version: 0.128.0

**Comment by Snayff** [comment]
There is no code change between these two images. Only two variables in a json config file, specifying the width and height, have been changed. 

640x360
![image](https://user-images.githubusercontent.com/23128268/95616638-0876ac80-0a62-11eb-9962-b9f02b8386ec.png)

1280x640
![image](https://user-images.githubusercontent.com/23128268/95616703-247a4e00-0a62-11eb-8c63-640b4228390c.png)


The `UIImage` is created like this:
```
        self.game_map = UIImage(
            relative_rect=Rect((0, 0), rect.size),
            image_surface=blank_surf,
            manager=manager,
            container=self.get_container(),
            object_id="#game_map",
        )
```
`self.game_map.rect` has the following x, y, width, height  (3, 3, 1280, 640) immediately after creation and `self.game_map.relative_rect` has (0, 0, 1280, 640).


Here is the update code that runs each frame, to scale the camera image to fit the `UIImage`.
```
    def _update_game_map(self):
        """
        Update the game map to show the current tiles and entities
        """
        # create new surface for the game map
        map_width = self._base_width
        map_height = self._base_height
        map_surf = Surface((map_width, map_height), SRCALPHA)

        # draw tiles
        for tile in self.current_tiles:
            self._draw_surface(tile.sprite, map_surf, (tile.x, tile.y))

        # draw entities
        from scripts.engine.core import queries
        for entity, (pos, aesthetic) in queries.position_and_aesthetic:
            # if part of entity in camera view get their tile offset
            for offset in pos.offsets:
                src_area = Rect(offset[0] * TILE_SIZE, offset[1] * TILE_SIZE, TILE_SIZE, TILE_SIZE)
                position = (pos.x + offset[0], pos.y + offset[1])
                draw_position = (aesthetic.draw_x + offset[0], aesthetic.draw_y + offset[1])
                if self.is_in_camera_view(position):
                    tile = world.get_tile(position)
                    if tile.is_visible or self.ignore_fov:
                        self._draw_surface(aesthetic.current_sprite, map_surf, draw_position, src_area)

        scaled_surf = pygame.transform.scale(map_surf, (self.game_map.rect.width, self.game_map.rect.height))

        self.game_map.set_image(scaled_surf)
```
`self._base_width` is 640 and `self.base_height` is 360. `self.game_map` rect values havent changed.

I don't know why it has moved left. The surface goes off the screen so it isnt that it has been clipped.

**Comment by DaFluffyPotato** [comment]
Should be fixed with the WIP camera overhaul (#136). Will close after merge.
640x360:
![image](https://user-images.githubusercontent.com/28032741/101314125-dbf2cd00-3825-11eb-95cd-dc601987d3e6.png)
1920x1080:
![image](https://user-images.githubusercontent.com/28032741/101314140-e6ad6200-3825-11eb-84d7-44d05dc63279.png)

**Comment by Snayff** [comment]
Thank you for the update. It doesn't look like the GUI is scaling properly
(text size doesn't scale, skill bar doesn't scale) but agree that the issue
of scaling making the GUI blurry looks resolved.

**Comment by DaFluffyPotato** [comment]
The GUI scaling you're asking for is more of feature that hasn't been added than a bug.

**Comment by Snayff** [comment]
Agreed! I wasn't so much asking for it as clarifying for posterity.
