### ISSUE TITLE
Can't Click on Skill Bar

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#115]
Describe the bug
Can no longer click on the Skill Bar to trigger targeting mode.

Expected behaviour
Should be able to click to trigger targeting mode and have the skill activated. 

Platform:
OS: Windows 10
Engine Version: 0.130.0

**Comment by DaFluffyPotato** [comment]
Fixed with pull #251. This was more of a nonexistent feature than a bug. lol
