### ISSUE TITLE
Refined Camera

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#136]
**Describe the solution you'd like**
A Camera that can display the game map, entities and lighting. Also provide an interface for interacting with those same things. 

**Specify the Feature's requirements**
- Only what is within a light and within the field of view of the Camera's target is drawn. 
- The Camera can target any entity. 
- The Camera will follow the target by moving to keep the target out of the camera's edge.
  - The size of the edge is set in number of tiles. 
  - The Camera cannot move outside of the game map. (meaning if the camera is in the top left of the map and the target moves to the top left corner of the Camera that the Camera would not move further)
- The game can scale to any 16:9 resolution.
- The Camera shows the same amount of tiles, regardless of the resolution of the game. 
- Light should not create a blank line where it touches walls. 
- The LightBox always effects those tiles shown in the Camera. 
- Moving the mouse over the Camera sets the currently selected tile. 
- The current selected tile is highlighted.  (any minor effect to indicate it is highlighted. highlighted edge?)
- Clicking on the Camera with the mouse fires an event that contains the x y coordinates of the clicked tile. 

**Any additional context**
Fixing this should also fix #111 and #114.

Removed requirements:
- The game can only be a 16:9 resolution.

**Comment by Snayff** [comment]
More info on the scaling #111 and https://github.com/MyreMylar/pygame_gui/issues/158#issuecomment-701966091 where discuss with pygame gui dev.

**Comment by DaFluffyPotato** [comment]
"If you're planning on using pixel art (which I'd recommend for performance and art cost reasons), I heavily advise against building scaling into the camera in the way you seem to be discussing. It's much simpler (less prone to bugs and easier to implement) and performs much better if you render everything onto a surface at a base resolution then scale.
also, Pygame 2 has a SCALED display argument that scales for you and uses GPU acceleration.
I haven't tried that part myself though."

**Comment by Snayff** [comment]
Updated requirements. Refined language, added some new ones.

**Comment by DaFluffyPotato** [comment]
Here's the status with strikethroughs on items that have been dealt with (partially for my own reference):
- ~~Only what is within a light and within the field of view of the Camera's target is drawn.~~ (_field of view is applied, but calculating what's visible according to the lighting will end up being more expensive than just rendering everything and letting the mask take care of it in most cases_)
- ~~The Camera can target any entity.~~
- ~~The Camera will follow the target by moving to keep the target out of the camera's edge.~~
- The size of the edge is set in number of tiles.
- ~~The Camera cannot move outside of the game map. (meaning if the camera is in the top left of the map and the target moves to the top left corner of the Camera that the Camera would not move further)~~
- ~~The game can scale to any 16:9 resolution.~~
- ~~The game can only be a 16:9 resolution.~~ (_this should not be enforced by the camera object and isn't necessary for the current milestone, so I won't be dealing with this issue here_)
- ~~The Camera shows the same amount of tiles, regardless of the resolution of the game.~~
- ~~Light should not create a blank line where it touches walls.~~
- ~~The LightBox always effects those tiles shown in the Camera.~~ (_unless I'm misunderstanding, this has never been an issue_)
- Moving the mouse over the Camera sets the currently selected tile.
- The current selected tile is highlighted. (any minor effect to indicate it is highlighted. highlighted edge?)
- Clicking on the Camera with the mouse fires an event that contains the x y coordinates of the clicked tile.

**Comment by DaFluffyPotato** [comment]
Completed by merge #219.
