### ISSUE TITLE
Add installation procedure to README

### ISSUE THREAD

**Issue by Aareon** [Snayff/notquiteparadise#138]
**Describe the solution you'd like**
Add installation steps to README (and the gh pages as well)

**Specify the Feature's requirements**
* Describe `poetry` and [how to](https://python-poetry.org/docs/#installation) install it
* Describe how to `git clone`
* `poetry install` will install dependencies
* `poetry build`
* `poetry run`

**Additional context**
It would also be pretty nifty if we could have a helper script to do installation for you.

**Comment by Aareon** [comment]
I just found out that `poetry build` and `poetry run` don't work in this case.
[This](https://github.com/Snayff/notquiteparadise/blob/develop/CONTRIBUTING.md#getting-started) describes installation.

Personally, I'd rather not use Poetry if I'm not actively developing, so I just used
```py
py -3.8 -m venv venv
.\venv\Scripts\activate
pip install pygame tcod snecs pygame-gui pytweening
```

**Comment by Snayff** [comment]
Great suggestion! I'll look at this after I finish the current branch. 

P.S. I am currently scoping for getting to a playable build so if you fancy giving issues a thumbs up if you're interested or thumbs down if you're not it would help the prioritisation.
