### ISSUE TITLE
Player Targeting System

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#152]
## Describe the solution you'd like
Allow the player to use a targeting grid to target their skills. 

## Specify the Feature's requirements
- The player is able to trigger a targeting mode by selecting a skill.  (via mouse, keyboard etc.)
- Successfully using a skill in targeting mode ends the targeting mode. 
- The targeting mode can be in 1 of 3 versions:
  - Able to target any valid tile within line of sight and the max skill range. (target a tile, "Tile")
  - Able to target a valid tile adjacent to the player in the directions as set by the skill (target a direction, "Direction")
  - Able to target self only (auto target, "Auto").
- During targeting mode valid tiles under valid targets are highlighted. 
- When in the Target Tile version of the targeting mode the line of tiles between the player and the targeted tile are highlighted. 
- The player is able to exit Targeting Mode without using a skill

## Additional Information
For "When in the Target Tile version of the targeting mode the line of tiles between the player and the targeted tile are highlighted. ":
Example of selecting a valid tile: 
![image](https://user-images.githubusercontent.com/23128268/102793679-26398980-43a2-11eb-9bd2-92925f8a1f37.png)
Another example of selecting a valid tile:
![image](https://user-images.githubusercontent.com/23128268/102793856-6436ad80-43a2-11eb-869f-09b6956e7a4d.png)
Example of selecting an invalid tile (the last tile is an invalid selection):
![image](https://user-images.githubusercontent.com/23128268/102794204-ecb54e00-43a2-11eb-8290-678ea2c06e86.png)

For "During targeting mode valid tiles under valid targets are highlighted. ":
Example of valid tiles being highlighted:
![image](https://user-images.githubusercontent.com/23128268/102812693-5e02fa00-43bf-11eb-882c-f34203af46d1.png)

**Comment by DaFluffyPotato** [comment]
Update from #221.
- ~~The player is able to trigger a targeting mode by selecting a skill. (via mouse, keyboard etc.)~~
- ~~Successfully using a skill in targeting mode ends the targeting mode.~~
- The targeting mode can be in 1 of 3 versions:
  - Able to target any valid tile within line of sight and the max skill range. (target tile)
  - ~~Able to target a valid tile adjacent to the player in the directions as set by the skill (target direction)~~
  - ~~Able to target self only (auto target).~~
- During targeting mode valid tiles under valid targets are highlighted.
- When in the Target Tile version of the targeting mode the line of tiles between the player and the targeted tile are highlighted.

**Comment by Snayff** [comment]
At the moment it looks like non-valid tiles are being highlighted:
![image](https://user-images.githubusercontent.com/23128268/102913001-08d5ef80-4476-11eb-8c33-fbaa867b597d.png)

There is also no way to exit targeting mode without using a skill, though that wasnt a requirement. I have added that as a requirement now.

**Comment by Snayff** [comment]
We might want to refine the Skill definition once you've done this. Currently there are several Optional attributes for a skill that are only required for one of the 3 targeting methods.  Let's see where we end up, but it should be a small change if we do need it. I've commented up the Skill class to help identify which bits are required.

We might need to do something similar with the delivery methods (projectile, delayed etc.).

**Comment by Snayff** [comment]
Just noticed that the camera is processing the intent.  Ideally the camera shouldnt be the thing to process the intent - the camera might change in response to the intent and generate new events but the actual parsing of the intent should be with the rest of the intent code.

**Comment by Snayff** [comment]
FYI, there is a new attribute on the Skill class, `cast_tags`, which are used to determine what Tiles are valid to cast on. `target_tags` now refer to _only_ valid targets for resolving the Skill.

**Comment by DaFluffyPotato** [comment]
There are some structural issues and minor bugs that need to be fixed, but the core feature set has been merged in #251.
