### ISSUE TITLE
Tile Info Only Handles Actors

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#242]
## The Bug
Mousing over projectile doesnt show information and also prevents the tile being highlighted. 

## Reproduction Instructions
Detail the steps to reproduce the bug. 

1. During player turn, with a projectile in view. 
2. Mouse over projectile and surrounding tiles. 

## Expected behaviour
Entities under the mouse are described in the Tile Info

## Screenshots
![vhCaLZpqeH](https://user-images.githubusercontent.com/23128268/104094911-c3922a00-528b-11eb-9338-b9548e53b1cd.gif)

## Platform
Describe the system and setup you were using when the bug happened. 

 - OS: Windows 10
 - Python Version: 3.8
 - NQP Version: 0.145.0

## Log Output/Stack Trace
N/A

**Comment by DaFluffyPotato** [comment]
This appears to be another unimplemented feature. Projectiles aren't like the other entities and the tile_info/actor_info elements don't have the code to show them.

**Comment by DaFluffyPotato** [comment]
The croc projectile names are too long and stats like health/stamina are shown. A feature issue should probably be opened with the specifications for the formatting of projectiles. #253 fixes this specific issue though.
