### ISSUE TITLE
Unintended "Knockback" from Projectiles

### ISSUE THREAD

**Issue by DaFluffyPotato** [Snayff/notquiteparadise#256]
## The Bug
Getting hit by a projectile by moving into it will sometimes knock the player back. (Presumably because the projectile updates the position of both entities instead of just itself.)

## Reproduction Instructions
Run into projectiles.

## Expected behaviour
Projectiles should have no knockback.

**Comment by Snayff** [comment]
This should be resolved by #260.
Edit:
Sort of? Doesnt trigger at all, which _does_ mean no knockback!
![image](https://user-images.githubusercontent.com/23128268/106587473-93b00c80-6541-11eb-91b7-3ea47ea6e15b.png)

**Comment by DaFluffyPotato** [comment]
So it's just reverted to #228. lol
